'use client'

import { useState, useEffect } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { createClient } from '@/lib/supabase/client'
import { FeedSection } from '@/components/jobs/FeedSection'
import { computeMatchScore } from '@/lib/ai/match-engine'
import type { JobMatch, UserProfile, JobRow } from '@/lib/types/database'

type FeedTab = 'best_matches' | 'new_near_you' | 'high_probability'

const TABS: { key: FeedTab; label: string }[] = [
  { key: 'best_matches', label: 'Best Matches' },
  { key: 'new_near_you', label: 'Near You' },
  { key: 'high_probability', label: 'Quick Hire' },
]

const SCAN_STATES = [
  'Scanning jobs in your area…',
  'Matching to your schedule…',
  'Ranking by fit…',
]

export default function DashboardPage() {
  const [userName, setUserName] = useState('')
  const [activeTab, setActiveTab] = useState<FeedTab>('best_matches')
  const [savedJobs, setSavedJobs] = useState<string[]>([])
  const [isLoading, setIsLoading] = useState(true)
  const [scanIdx, setScanIdx] = useState(0)
  const [jobs, setJobs] = useState<Record<FeedTab, JobMatch[]>>({
    best_matches: [],
    new_near_you: [],
    high_probability: [],
  })
  const [totalCount, setTotalCount] = useState(0)

  useEffect(() => {
    // Animate scan text while data loads
    let i = 0
    const interval = setInterval(() => {
      i++
      setScanIdx(Math.min(i, SCAN_STATES.length - 1))
    }, 700)

    loadDashboard().finally(() => {
      clearInterval(interval)
      setTimeout(() => setIsLoading(false), 300)
    })

    return () => clearInterval(interval)
  }, [])

  async function loadDashboard() {
    const supabase = createClient()
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return

    // Load profile and saved jobs in parallel
    const [profileRes, applicationsRes] = await Promise.all([
      supabase.from('users').select('*').eq('id', user.id).single(),
      supabase.from('applications').select('job_id').eq('user_id', user.id),
    ])

    if (profileRes.data?.name) {
      setUserName(profileRes.data.name.split(' ')[0])
    }

    if (applicationsRes.data) {
      setSavedJobs(applicationsRes.data.map((a: { job_id: string }) => a.job_id))
    }

    // Try pre-computed matches first (generated by cron or post-onboarding)
    const { data: preComputed } = await supabase
      .from('job_matches')
      .select(`
        match_score,
        match_explanation,
        feed_section,
        jobs (*)
      `)
      .eq('user_id', user.id)
      .order('match_score', { ascending: false })
      .limit(100)

    if (preComputed && preComputed.length > 0) {
      // Cast needed: Supabase types can't infer join shape without Relationships declarations
      type RawMatch = { match_score: number; match_explanation: string | null; feed_section: string; jobs: unknown }
      const matchedJobs: JobMatch[] = (preComputed as RawMatch[])
        .filter((m) => m.jobs && typeof m.jobs === 'object')
        .map((m) => ({
          ...(m.jobs as JobRow),
          match_score: m.match_score,
          match_explanation: m.match_explanation ?? '',
        }))

      classifyAndSetJobs(matchedJobs)
      setTotalCount(matchedJobs.length)
      return
    }

    // Fallback: run match engine on-the-fly if no pre-computed matches
    // This handles new users before the cron has run
    if (!profileRes.data) return

    const { data: allJobs } = await supabase
      .from('jobs')
      .select('*')
      .eq('status', 'active')
      .eq('is_active', true)
      .eq('verification_status', 'verified')
      .lt('scam_risk_score', 70)
      .limit(300)

    if (!allJobs || allJobs.length === 0) return

    const userProfile = profileRes.data as unknown as UserProfile
    const scored: JobMatch[] = []

    for (const job of allJobs as JobRow[]) {
      if (userProfile.age && userProfile.age < job.min_age) continue
      const { match_score, match_explanation } = computeMatchScore(userProfile, job)
      if (match_score < 30) continue
      scored.push({ ...job, match_score, match_explanation })
    }

    scored.sort((a, b) => b.match_score - a.match_score)
    classifyAndSetJobs(scored)
    setTotalCount(scored.length)

    // Kick off background pre-computation for next load
    fetch('/api/match-user', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ user_id: user.id }),
    }).catch(() => {/* non-critical */})
  }

  function classifyAndSetJobs(matched: JobMatch[]) {
    setJobs({
      best_matches: matched.filter((j) => j.match_score >= 70).slice(0, 25),
      new_near_you: matched
        .filter((j) => j.match_score >= 45)
        .sort((a, b) => {
          // Sort by location proximity (same zip = highest)
          const aLocal = a.zip_code?.slice(0, 3)
          const bLocal = b.zip_code?.slice(0, 3)
          return (aLocal === bLocal ? 1 : 0) - (bLocal === aLocal ? 1 : 0) + (b.match_score - a.match_score) * 0.01
        })
        .slice(0, 20),
      high_probability: matched
        .filter((j) => j.hiring_speed_score >= 78 && j.match_score >= 45)
        .sort((a, b) => b.hiring_speed_score - a.hiring_speed_score)
        .slice(0, 20),
    })
  }

  async function handleSave(jobId: string) {
    const supabase = createClient()
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return

    if (savedJobs.includes(jobId)) {
      setSavedJobs((prev) => prev.filter((id) => id !== jobId))
      await supabase.from('applications').delete().eq('user_id', user.id).eq('job_id', jobId)
    } else {
      setSavedJobs((prev) => [...prev, jobId])
      await supabase.from('applications').upsert({
        user_id: user.id,
        job_id: jobId,
        status: 'saved',
      })
    }
  }

  const hour = new Date().getHours()
  const timeLabel = hour < 12 ? 'morning' : hour < 17 ? 'afternoon' : 'evening'

  return (
    <div className="flex flex-col min-h-full">

      {/* ── Header ── */}
      <div className="px-5 pt-12 pb-5">
        <motion.p
          initial={{ opacity: 0, y: -6 }}
          animate={{ opacity: 1, y: 0 }}
          style={{ fontSize: '14px', color: 'var(--et-muted)', fontWeight: 500 }}
        >
          Good {timeLabel}{userName ? `, ${userName}` : ''} 👋
        </motion.p>

        <motion.h1
          initial={{ opacity: 0, y: -4 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.07 }}
          style={{
            fontSize: '26px',
            fontWeight: 800,
            color: 'var(--et-ink)',
            letterSpacing: '-0.03em',
            marginTop: '3px',
            lineHeight: 1.15,
          }}
        >
          {isLoading
            ? 'Finding your matches…'
            : totalCount > 0
            ? `${totalCount} jobs matched for you`
            : 'Your job feed'}
        </motion.h1>

        <div style={{ marginTop: '6px', height: '18px' }}>
          <AnimatePresence mode="wait">
            {isLoading ? (
              <motion.div
                key={scanIdx}
                initial={{ opacity: 0, y: 4 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -4 }}
                transition={{ duration: 0.2 }}
                className="flex items-center gap-2"
              >
                <div className="flex gap-1">
                  <span className="typing-dot" />
                  <span className="typing-dot" />
                  <span className="typing-dot" />
                </div>
                <span style={{ fontSize: '12px', color: 'var(--et-blue)', fontWeight: 600 }}>
                  {SCAN_STATES[scanIdx]}
                </span>
              </motion.div>
            ) : (
              <motion.p
                key="ready"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                style={{ fontSize: '12px', color: 'var(--et-placeholder)' }}
              >
                {totalCount > 0 ? 'AI-matched · ranked by fit' : 'AI feed · updated daily'}
              </motion.p>
            )}
          </AnimatePresence>
        </div>
      </div>

      {/* ── Tab bar ── */}
      <div
        className="flex gap-2 px-5 pb-4 scrollbar-hide overflow-x-auto"
        style={{ WebkitOverflowScrolling: 'touch' } as React.CSSProperties}
      >
        {TABS.map(({ key, label }) => {
          const active = activeTab === key
          const count = jobs[key].length
          return (
            <motion.button
              key={key}
              whileTap={{ scale: 0.95 }}
              onClick={() => setActiveTab(key)}
              style={{
                flexShrink: 0,
                height: '36px',
                padding: '0 16px',
                borderRadius: 'var(--radius-full)',
                fontSize: '13px',
                fontWeight: active ? 700 : 500,
                border: active ? 'none' : '1.5px solid var(--et-border-mid)',
                background: active ? 'var(--et-blue)' : 'var(--et-surface)',
                color: active ? '#fff' : 'var(--et-subtle)',
                boxShadow: active ? 'var(--shadow-blue-sm)' : 'none',
                cursor: 'pointer',
                transition: 'all 0.15s ease',
                letterSpacing: '-0.01em',
              }}
            >
              {label}{!isLoading && count > 0 ? ` (${count})` : ''}
            </motion.button>
          )
        })}
      </div>

      {/* ── Feed ── */}
      <div className="px-4 pb-4">
        <AnimatePresence mode="wait">
          <motion.div
            key={activeTab}
            initial={{ opacity: 0, x: 10 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: -10 }}
            transition={{ duration: 0.2, ease: [0.22, 1, 0.36, 1] }}
          >
            {isLoading ? (
              <div className="flex flex-col gap-3">
                {[0, 1, 2].map((i) => (
                  <div
                    key={i}
                    className="card-elevated"
                    style={{ height: 200, animationDelay: `${i * 0.1}s` }}
                  >
                    <div className="px-5 pt-5 pb-4 flex items-start gap-4" style={{ borderBottom: '1px solid var(--et-border)' }}>
                      <div className="skeleton" style={{ width: 72, height: 72, borderRadius: '50%' }} />
                      <div className="flex-1 flex flex-col gap-2 pt-1">
                        <div className="skeleton" style={{ height: 12, width: '40%', borderRadius: 6 }} />
                        <div className="skeleton" style={{ height: 18, width: '70%', borderRadius: 6 }} />
                        <div className="skeleton" style={{ height: 12, width: '50%', borderRadius: 6 }} />
                      </div>
                    </div>
                    <div className="px-5 pt-4 flex flex-col gap-2">
                      <div className="skeleton" style={{ height: 12, width: '80%', borderRadius: 6 }} />
                      <div className="skeleton" style={{ height: 12, width: '60%', borderRadius: 6 }} />
                    </div>
                  </div>
                ))}
              </div>
            ) : (
              <FeedSection
                jobs={jobs[activeTab]}
                savedJobs={savedJobs}
                onSave={handleSave}
                emptyState={
                  activeTab === 'best_matches'
                    ? totalCount === 0
                      ? 'No jobs in the database yet — check back soon as we load new listings daily.'
                      : 'No strong matches yet. Try expanding your availability or transportation options.'
                    : activeTab === 'new_near_you'
                    ? 'No nearby jobs right now. We add new listings every day.'
                    : 'No fast-hiring employers matching your profile right now.'
                }
              />
            )}
          </motion.div>
        </AnimatePresence>
      </div>
    </div>
  )
}
